# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_profile_fk', models.IntegerField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
