# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehours',
            name='module_code',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
