# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_raised',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 17, 30, 54, 654183, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
