# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0005_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.IntegerField()),
                ('time_opened', models.DateTimeField()),
                ('time_closed', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(2, 'Abandon'), (1, 'Resolved'), (0, 'Pending')], default=0)),
                ('office_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalclerk_app.OfficeHours')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalclerk_app.Request')),
            ],
        ),
    ]
