# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0007_auto_20171118_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
