# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0009_auto_20171118_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='duration_minutes',
            new_name='duration_seconds',
        ),
    ]
