# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0011_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='foot_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='next_steps',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
