# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0014_auto_20180110_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='student', max_length=25),
            preserve_default=False,
        ),
    ]
