# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalclerk_app', '0015_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('upi', models.CharField(max_length=20)),
            ],
        ),
    ]
